Refactor, so that always the queries are constructed identically
tfenster/azdevops-vscode-simplify pull request #14
Opened 2022-11-26 16:49 UTC by DavidFeldhoff

Hi Tobias,

while working on #13 I noticed that we as well are not respecting the "hideWorkItemsWithState" setting.
I did not want to simply fix it, but refactored it instead in a way that the queries are created the same way, so that future changes can be implemented easier and more consistent which is why the PR is a bit bigger. If you have questions or don't like some changes, feel free to reach out to me.

2022-11-27 13:22 UTC, tfenster approved these changes

2022-11-27 16:49 UTC, tfenster requested changes
Please add a changelog entry

2022-11-28 06:27 UTC, DavidFeldhoff commented
Hi Tobias, you're right. I added the changelog entry. Can you please have a look again?

2022-11-28 06:28 UTC, tfenster submitted a review, later dismissed

2022-11-28 17:36 UTC, tfenster approved these changes

2022-11-28 17:47 UTC, merged