Expand active project
tfenster/azdevops-vscode-simplify pull request #15
Opened 2022-11-26 17:47 UTC by DavidFeldhoff

Hi Tobias, 

this PR expands the current active project, so it relates to #2.

Until now I did not solve the other requests that are in that issue (filtering out some organizations). But I think this small change would also be an improvement and we can tackle the other requests in a separate PR

2022-11-27 13:24 UTC, tfenster approved these changes

2022-11-27 16:49 UTC, tfenster requested changes
Please add a changelog entry

2022-11-28 06:29 UTC, DavidFeldhoff commented
Hi Tobias, I added the changelog entry, can you please have a look again?

2022-11-28 06:36 UTC, tfenster submitted a review, later dismissed

2022-11-28 20:20 UTC, tfenster approved these changes

2022-11-28 20:21 UTC, merged